### PR TITLE
Implement List directly instead of extending ArrayList.

### PR DESCRIPTION
**Pull request by johnou**
Closes https://github.com/brettwooldridge/HikariCP/issues/672 .

### CODE REVIEW

**Comment by johnou** [comment]
@brettwooldridge should be ok that FastList is no longer serializable?

**Comment by johnou** [comment]
CI build failure seems unrelated.. HikariCPCollectorTest.connectionClosed:74 » NoSuchMethod org.hamcrest.Matcher....

**Comment by PascalSchumacher** [comment]
Yes the failure also occurs without the changes of the pull request: https://travis-ci.org/brettwooldridge/HikariCP

This https://github.com/brettwooldridge/HikariCP/pull/681 should fix the issue.

**Comment by johnou** [comment]
@PascalSchumacher wdyt about simplifying the dependencies instead?

**Comment by PascalSchumacher** [comment]
I think that is much better. :+1:  I will close #681 .

**Comment by johnou** [comment]
@brettwooldridge PTAL.

**Comment by johnou** [comment]
Thanks @brettwooldridge!

**Pull request merged**
