### PR TITLE
Check the correct sql state and error code when unwrapping the except…

### PR DESCRIPTION
**Pull request by johnou**
…ion chain.

### CODE REVIEW

**Comment by johnou** [comment]
@brettwooldridge apologies for not catching this sooner.

**Comment by johnou** [comment]
@brettwooldridge any estimates on when we might see fixes for https://github.com/brettwooldridge/HikariCP/pull/723 and https://github.com/brettwooldridge/HikariCP/pull/724 in a release?

**Comment by brettwooldridge** [comment]
@johnou How about now?  I just published 2.5.1.

**Comment by johnou** [comment]
@brettwooldridge you rock!

**Comment by johnou** [comment]
@doom369 heads up.

**Comment by doom369** [comment]
@johnou @brettwooldridge everything works fine for 1 week in production already. Thanks!

**Comment by brettwooldridge** [comment]
Great.

**Pull request merged**
