### PR TITLE
Add pool metrics

### PR DESCRIPTION
**Pull request by matsumana**
Add metrics to alert when remaining pooled connections are insufficient in quantity.

### CODE REVIEW

**Comment by brettwooldridge** [comment]
These seem redundant as they are already available on the HikariPoolMXBean... why should they be duplicated?

**Comment by matsumana** [comment]
I'm using Spring Boot 2.0, micrometer and prometheus.

Please take a look the following metrics.
These are metrics which exported by that.

I think that there are 2 issues.

```

Exported by Spring Boot

# HELP jdbc_connections_active  
# TYPE jdbc_connections_active gauge
jdbc_connections_active{name="dataSource",} 0.0

# HELP jdbc_connections_max  
# TYPE jdbc_connections_max gauge
jdbc_connections_max{name="dataSource",} 60.0

# HELP jdbc_connections_min  
# TYPE jdbc_connections_min gauge
jdbc_connections_min{name="dataSource",} 50.0


Exported by HikariCP

# HELP hikaricp_connections_active Active connections
# TYPE hikaricp_connections_active gauge
hikaricp_connections_active{pool="HikariPool-1",} 0.0

# HELP hikaricp_connections Total connections
# TYPE hikaricp_connections gauge
hikaricp_connections{pool="HikariPool-1",} 33.0

# HELP hikaricp_connections_pending Pending threads
# TYPE hikaricp_connections_pending gauge
hikaricp_connections_pending{pool="HikariPool-1",} 0.0

# HELP hikaricp_connections_idle Idle connections
# TYPE hikaricp_connections_idle gauge
hikaricp_connections_idle{pool="HikariPool-1",} 33.0

# HELP hikaricp_connections_timeout_total Connection timeout total count
# TYPE hikaricp_connections_timeout_total counter
hikaricp_connections_timeout_total{pool="HikariPool-1",} 0.0

# HELP hikaricp_connections_creation_seconds Connection creation time
# TYPE hikaricp_connections_creation_seconds summary
hikaricp_connections_creation_seconds{pool="HikariPool-1",quantile="0.95",} 0.394264575
hikaricp_connections_creation_seconds_count{pool="HikariPool-1",} 32.0
hikaricp_connections_creation_seconds_sum{pool="HikariPool-1",} 8.058
hikaricp_connections_creation_seconds_max{pool="HikariPool-1",} 0.397

# HELP hikaricp_connections_acquire_seconds Connection acquire time
# TYPE hikaricp_connections_acquire_seconds summary
hikaricp_connections_acquire_seconds{pool="HikariPool-1",quantile="0.95",} 0.001048575
hikaricp_connections_acquire_seconds_count{pool="HikariPool-1",} 1.0
hikaricp_connections_acquire_seconds_sum{pool="HikariPool-1",} 0.001
hikaricp_connections_acquire_seconds_max{pool="HikariPool-1",} 0.001

# HELP hikaricp_connections_usage_seconds Connection usage time
# TYPE hikaricp_connections_usage_seconds summary
hikaricp_connections_usage_seconds{pool="HikariPool-1",quantile="0.95",} 1.216348159
hikaricp_connections_usage_seconds_count{pool="HikariPool-1",} 1.0
hikaricp_connections_usage_seconds_sum{pool="HikariPool-1",} 1.209
hikaricp_connections_usage_seconds_max{pool="HikariPool-1",} 1.209
```

1. IMHO, if the metrics' prefix on HikariCP is unified by `hikaricp_connections` it is easier to understand.

2. The label of the metric exported by Spring Boot is different from the label exported by HikariCP.
It migth be better to report this to Spring Boot. I'll do write an issue on the Spring Boot repository.

**Comment by brettwooldridge** [comment]
I understand.  If min/max connections are exposed as a metric, I would want to see that metric implemented across the other metric providers as well (DropWizard, Prometheus).  If those changes are included, I will accept the pull request.

**Comment by matsumana** [comment]
Thank you for the reply.

I updated the following test code in this PR.
Is that not enough?

- CodaHaleMetricsTrackerTest
- MicrometerMetricsTrackerTest
- HikariCPCollectorTest

if so, would you tell me  what kind of test should be added?

**Comment by matsumana** [comment]
Hello. Thank you for the merging.
btw, when will a new version be released?
I'd like to use this PR and #1108 as soon as possible.

**Pull request merged**
