### PR TITLE
Added missing dependencies

### PR DESCRIPTION
**Pull request by cowwoc**

### CODE REVIEW

**Comment by cowwoc** [comment]
@brettwooldridge So good news. `module-info.java` is being found. But it was missing some dependencies. Please let me know once the new SNAPSHOT is ready for testing.

**Comment by cowwoc** [comment]
If I don't copy the class files over, I get the following error:

```
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:14: error: package is empty or does not exist: com.zaxxer.hikari
   exports com.zaxxer.hikari;
                     ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:15: error: package is empty or does not exist: com.zaxxer.hikari.hibernate
   exports com.zaxxer.hikari.hibernate;
                            ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:16: error: package is empty or does not exist: com.zaxxer.hikari.metrics
   exports com.zaxxer.hikari.metrics;
                            ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:17: error: package is empty or does not exist: com.zaxxer.hikari.metrics.dropwizard
   exports com.zaxxer.hikari.metrics.dropwizard;
                                    ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:18: error: package is empty or does not exist: com.zaxxer.hikari.metrics.micrometer
   exports com.zaxxer.hikari.metrics.micrometer;
                                    ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:19: error: package is empty or does not exist: com.zaxxer.hikari.metrics.prometheus
   exports com.zaxxer.hikari.metrics.prometheus;
                                    ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:20: error: package is empty or does not exist: com.zaxxer.hikari.pool
   exports com.zaxxer.hikari.pool;
                            ^
C:\Users\Gili\Documents\HikariCP\src\main\java11\module-info.java:21: error: package is empty or does not exist: com.zaxxer.hikari.util
   exports com.zaxxer.hikari.util;
                            ^
8 errors

```

I tried various tricks but couldn't figure it out so I think we're going to have to keep it for now.

**Comment by brettwooldridge** [comment]
@cowwoc New snapshot deployed.

**Comment by brettwooldridge** [comment]
@cowwoc Let me know if it works.  4am here in Japan, so I'll be headed off to bed shortly and will pick it up tomorrow.

**Comment by brettwooldridge** [comment]
@cowwoc of course you can build a local jar with ``mvn clean package -Dmaven.test.skip=true``.

**Comment by cowwoc** [comment]
@brettwooldridge Good point. Fortunately we're done. The latest SNAPSHOT works for me.

**Pull request merged**
