### PR TITLE
Changed ProxyLeakTask to log current stack trace for thread holding t…

### PR DESCRIPTION
**Pull request by pmalon**
…he connection instead of entry point of the transaction

Before:
```
 [memento-master housekeeper] [] [] [] WARN com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for org.mariadb.jdbc.MariaDbConnection@3d10c6e8 on thread Grizzly(3), stack trace follows
 java.lang.Exception: Apparent connection leak detected
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
    at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
    at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
    at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
    at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:162)
    at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1435)
    at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:61)
    at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:170)
    at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
    at com.phorest.memento.server.rs.resource.AppointmentPatchResourceBean$$EnhancerBySpringCGLIB$$ef6398d8.patch(<generated>)
    at sun.reflect.GeneratedMethodAccessor1158.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
```

After:
```
2020-09-11 20:48:24,570 [memento-master housekeeper] [] [] [] WARN  com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for org.mariadb.jdbc.MariaDbConnection@16e4db59 on thread Grizzly(3), stack trace follows
java.lang.Exception: Apparent connection leak detected
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.google.common.util.concurrent.Uninterruptibles.sleepUninterruptibly(Uninterruptibles.java:275)
	at com.phorest.memento.server.rs.resource.AppointmentPatchResourceBean.patch(AppointmentPatchResourceBean.java:338)
	at com.phorest.memento.server.rs.resource.AppointmentPatchResourceBean$$FastClassBySpringCGLIB$$ee887680.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.phorest.memento.server.rs.resource.interceptor.LinksInterceptor.injectLinks(LinksInterceptor.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:620)
```
With this change in place it should be a lot easier to search for a root cause of the connection leak.

### CODE REVIEW

**Comment by quaff** [comment]
It sounds good.

**Comment by brettwooldridge** [comment]
@pmalon @quaff Wait, what? How is that clearer? What if the thread has already exited? What if the thread that acquired the connection is from a threadpool that runs various kinds of tasks? And the pool thread is currently executing completely unrelated code?

**Comment by quaff** [comment]
> @pmalon @quaff Wait, what? How is that clearer? What if the thread has already exited? What if the thread that acquired the connection is from a threadpool that runs various kinds of tasks? And the pool thread is currently executing completely unrelated code?

You are right.

**Comment by pmalon** [comment]
Lads, you have described an edge where this proposed approach wouldn’t be useful, whereas now (at least in my opinion) it doesn’t help much in typical situations (where connection is acquired on the same thread that runs the whole transaction logic). We had a real life scenario where we weren't able to identify root cause of the "apparent connection leak" problem as stacktraces where just showing the entry points for the transactions and not where threads holding the connections were when connection was identified as "leaked". With those changes we identified source of the problem next time it occurred.  
It seems that I am not the only one not finding current solution particularly useful - see: [here](https://stackoverflow.com/questions/54883940/apparent-connection-leak-detected-with-hikari-cp) and 
[here](https://forum.camunda.org/t/connection-leak-detection-triggered/22200)
 
Perhaps a good compromise would be to introduce configuration property to decide whether it should log entry point of the transaction or current stack trace of the thread that acquired the connection?

**Comment by brettwooldridge** [comment]
@pmalon I think the current case that leak detection covers is by far the most common case. However, I understand there may be programming patterns where it does not provide enough context to identify the source of the leak. I would agree to a system property, for example ``hikaricp.leak.currentStack`` (``=true``), to control the new behavior.

**Comment by pmalon** [comment]
@brettwooldridge thank you for your understanding. 
I'll make suggested change (most likely over the weekend)

**Comment by lfbayer** [comment]
I'm closing this pull request as the suggested change of adding a system property was never made.

**Pull request closed without merging**
