### PR TITLE
Make generated proxy class final

### PR DESCRIPTION
**Pull request by quaff**
The final modifier is overridden by public modifier before this commit

### CODE REVIEW

**Comment by quaff** [comment]
Could anyone explain why `codecov/project` failed?

**Review by johnou — APPROVED** [review]

**Comment by johnou** [comment]
lgtm nice catch! cc @brettwooldridge

**Comment by johnou** [comment]
ping @brettwooldridge

**Comment by johnou** [comment]
ping @brettwooldridge happy new year

**Comment by brettwooldridge** [comment]
@johnou Happy New Year

**Pull request merged**
