### PR TITLE
removed redundant creationTime. lastAceess is initialized at creation as

### PR DESCRIPTION
**Pull request by nitincchauhan**
well.

### CODE REVIEW

**Comment by brettwooldridge** [comment]
I am particularly interested in seeing the ``creationTIme`` (via toString()), independent of the ``lastAccess`` time.  That's why it is there.

**Comment by nitincchauhan** [comment]
in Log it would show creation time formatted, besides that there is no 'real' use.

**Comment by brettwooldridge** [comment]
That *is* the real use.  It is there for my troubleshooting, because there were several bugs in the past about connections not being retired.  It should not be removed.

**Comment by nitincchauhan** [comment]
log also shows when connection was last accessed. how creation time would be more useful than this?

**Comment by nitincchauhan** [comment]
now changed lastOpenTime to update on borrow so you may use it as well instead.

**Comment by brettwooldridge** [comment]
There was some trickery going on, for performance, that probably wasn't apparent...

[This code](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L176):
```java
metricsContext.setConnectionLastOpen(poolEntry, now);
```
calls [this method](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/metrics/MetricsTracker.java#L69) when there are no metrics being recorded:
```java
public void setConnectionLastOpen(final PoolEntry bagEntry, final long now) {
     // do nothing
}
```
which you can see actually does *nothing*.  Only when metrics are *enabled* does ``poolEntry.lastOpenTime`` get set in the ``CodaHaleMetricsTracker`` [version of that method](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/metrics/CodaHaleMetricsTracker.java#L130).

That avoids a *volatile* access in the "hot path" when metrics are off.  Here is the difference in the benchmark between the current code and your pull:
```
Current:
Benchmark                       Mode  Cnt      Score     Error   Units
ConnectionBench.cycleCnnection  thrpt   48  29497.680 ± 396.660  ops/ms

Pull:
Benchmark                       Mode  Cnt      Score     Error   Units
ConnectionBench.cycleCnnection  thrpt   48  26988.262 ± 737.596  ops/ms
```

**Comment by nitincchauhan** [comment]
I was aware of this trick  ;)
This change is first step to protect pool entry and its fields... With your help, Hope to achieve both performance as well as protection from this start.

**Comment by nitincchauhan** [comment]
lastOpenTime is initialized only in getConnection() so it can be made non-volatile. it is ok to have old value in metrics if at all access happens with initialization exactly same time.

**Comment by nitincchauhan** [comment]
Now with all these changes, I hope difference in benchmark would be acceptable.

**Comment by nitincchauhan** [comment]
Also, as requested in https://github.com/brettwooldridge/HikariCP/issues/412, MetricsContext can not interfere with pool entry anymore.

**Pull request merged**
