### PR TITLE
Add support for copying state of final Collection and Map

### PR DESCRIPTION
**Pull request by quaff**
And mark Properties field as final

### CODE REVIEW

**Comment by brettwooldridge** [comment]
What problem is this solving?

**Comment by quaff** [comment]
> What problem is this solving?

We can make them `final` for immutability.

```java
private final Properties dataSourceProperties = new Properties();
```

**Comment by brettwooldridge** [comment]
This doesn't protect anything real. It protects the *reference* but the properties themselves are still mutable.

**Comment by quaff** [comment]
> This doesn't protect anything real. It protects the _reference_ but the properties themselves are still mutable.

Yes, just for improving coding style, feel free to close it if you think it's not worthy.

**Pull request closed without merging**
