### PR TITLE
Log better message when connection was evicted or dead

### PR DESCRIPTION
**Pull request by wvuong**
This minor change in the logging lets us know which condition (was evicted or is dead) caused the connection to be closed.  The "dead" condition is interesting to us because that means the JDBC4 connection.isValid() failed and we can better pin the blame on the network or database server.

### CODE REVIEW

**Comment by brettwooldridge** [comment]
Good point.  Definintely do not want to call ``isConnectionAlive()`` unless absolutely necessary.  Evictions/dead connections are rare enough that paying the cost of re-evaluation *inside* the original conditional would be better.

**Comment by johnou** [comment]
@brettwooldridge while I am not as experienced as you with byte code optimisation could I trouble you to explain why there are two try blocks? I was thinking something like this might be "ideal"

```java
public Connection getConnection(final long hardTimeout) throws SQLException
{
   suspendResumeLock.acquire();
   final long startTime = currentTime();
   PoolEntry poolEntry = null;
   try {
      long timeout = hardTimeout;
      do {
         poolEntry = connectionBag.borrow(timeout, MILLISECONDS);
         if (poolEntry == null) {
            break; // We timed out... break and throw exception
         }

         final long now = currentTime();
         if (poolEntry.isMarkedEvicted() || (elapsedMillis(poolEntry.lastAccessed, now) > ALIVE_BYPASS_WINDOW_MS && !isConnectionAlive(poolEntry.connection))) {
            closeConnection(poolEntry, poolEntry.isMarkedEvicted() ? EVICTED_CONNECTION_MESSAGE : DEAD_CONNECTION_MESSAGE); // Throw away the dead connection (passed max age or failed alive test)
            timeout = hardTimeout - elapsedMillis(startTime);
         }
         else {
            metricsTracker.recordBorrowStats(poolEntry, startTime);
            return poolEntry.createProxyConnection(leakTask.schedule(poolEntry), now);
         }
      } while (timeout > 0L);

      metricsTracker.recordBorrowTimeoutStats(startTime);
   }
   catch (InterruptedException e) {
      if (poolEntry != null) {
         poolEntry.recycle(startTime);
      }
      Thread.currentThread().interrupt();
      throw new SQLException(poolName + " - Interrupted during connection acquisition", e);
   }
   finally {
      suspendResumeLock.release();
   }

   throw createTimeoutException(startTime);
}
```

**Comment by johnou** [comment]
@brettwooldridge as there has not been further contact from wvuong I went ahead and made the changes as per our discussion https://github.com/brettwooldridge/HikariCP/pull/977

**Comment by wvuong** [comment]
Hey, sorry for ghosting this - closing mine because #977 is doing it better.

**Pull request closed without merging**
