### PR TITLE
Fixing Redshift specific disconnect error

### PR DESCRIPTION
**Pull request by xstevens**
Fixes: https://github.com/brettwooldridge/HikariCP/issues/650

### CODE REVIEW

**Comment by brettwooldridge** [comment]
If I can ask a favor, before I merge this pull can you check Redshift for additional disconnection codes that should be registered as well?

**Comment by xstevens** [comment]
@brettwooldridge Sure no problem. I'll take a look. I did a bit of searching and HY000 seems like a pretty generic code for some databases, so I'm a little worried that this may have other side effects. I'm not super familiar with SQLSTATE codes.

**Comment by johnou** [comment]
At least mysql docs state that error indicates no DNS resolution for the given endpoint. 
Error 2005 (HY000): Unknown MySQL Server Host
http://dev.mysql.com/doc/refman/5.7/en/error-messages-client.html#error_cr_unknown_host

**Comment by johnou** [comment]
@xstevens guess we can close this in favour of https://github.com/brettwooldridge/HikariCP/commit/21eedd550258f6a33bc0f4b22579366afe7f4e62 ?

**Comment by xstevens** [comment]
@johnou Yes, thanks!

**Pull request closed without merging**
