### PR TITLE
Log better message when connection was evicted or dead.

### PR DESCRIPTION
**Pull request by johnou**
Closes https://github.com/brettwooldridge/HikariCP/pull/842

### CODE REVIEW

**Comment by johnou** [comment]
@brettwooldridge ptal, let me know if further changes are required.

**Comment by brettwooldridge** [comment]
@johnou Thanks for the contribution. 🥇

**Comment by brettwooldridge** [comment]
@johnou HikariCP v2.7.2 containing this fix has been released.

**Comment by johnou** [comment]
ping @wvuong

**Pull request merged**
